spring.application.name=Note keeper backend


spring.datasource.url=jdbc:mysql://localhost:3306/note-keeper
spring.datasource.username=root
spring.datasource.password=Saurav@2999
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey="c2F1cmF2IGt1bWFyIHNpbmdoIG1vdmllIGFjhiu2343kjj4b5b4kjkjh5344jb4b4jb4jb"

# 2 hours in milliseconds (1000 * 60 * 60 * 2)
jwt.expiration=7200000